name: Run Minecraft Bot with Ollama

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install ollama requests

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Git
        run: |
          sudo apt-get update
          sudo apt-get install -y git

      - name: Configure Git to use HTTPS
        run: |
          git config --global url."https://github.com/ ".insteadOf git@github.com:
          git config --global url."https://".insteadOf git://

      - name: Clear NPM and Git cache
        run: |
          npm cache clean --force
          rm -rf ~/.npm/_git-remotes/

      - name: Install Node dependencies
        run: |
          npm install
          npm install commander --save-dev
          npm install mineflayer --save

      - name: Install minecraft-data from GitHub (HTTPS)
        run: |
          npm install git+https://github.com/PrismarineJS/minecraft-data.git #main --save

      - name: Run Bot Executor
        env:
          MINECRAFT_COMMAND: "Construa uma casa de madeira com 2 andares"
        run: |
          python src/bot_executor.py
