name: Run Minecraft Bot with Ollama

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Show current directory files
        run: |
          echo "Current directory:"
          ls -la

      - name: Install Node dependencies
        run: |
          npm install

      - name: Install extra dependencies
        run: |
          npm install commander --save-dev
          npm install mineflayer --save

      - name: Run Bot Executor
        env:
          MINECRAFT_COMMAND: "Construa uma casa de madeira com 2 andares"
        run: |
          python src/bot_executor.py
